apiVersion: v1
kind: Service
metadata:
  name: ai-engine
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "infrawhisper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.aiEngine.service.type }}
  selector:
    app: ai-engine
  ports:
    - name: http
      port: {{ .Values.aiEngine.service.port }}
      targetPort: http
