apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrawhisper
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mejba13/infrawhisper.git
    targetRevision: main
    path: deploy/helm/infrawhisper
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: infrawhisper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
